name: Erleans Elixir Example tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: test
          POSTGRES_DB: test

    steps:
    - uses: actions/checkout@v1.0.0
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: 22.x
        elixir-version: 1.9.x
    - name: Fetch deps
      run: mix deps.get
    - name: Run tests
      run: mix test
